os: windows
language: sh

deploy:
  skip_cleanup: true
  on:
    branch: master
    # tags: true
  provider: script
  script:
    - pip install twine
    - python ./setup.py bdist_wheel
    - >
      twine upload
      --username "pupil-labs"
      --password "$PYPI_APITOKEN"
      ./dist/*
