os: windows
language: sh

before_install:
  - python --version || true
  - choco list --local-only
install: pip install -U pip setuptools twine wheel

deploy:
  on:
    branch: master
    # tags: true
  provider: pypi
  user: pupil-labs
  password : $PYPI_APITOKEN
  distributions: "bdist_wheel"
