language: python
python: "3.6"

install: pip3 install wheel
script: python3 ./setup.py sdist bdist_wheel

deploy:
  skip_cleanup: true
  on:
    branch: master
    tags: true
  provider: script
  script: bash ./.travis/deploy.sh
