os: windows
language: sh

before_install: choco install python --version 3.6.8
env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
install: pip install -U pip setuptools twine wheel
script: python --version

deploy:
  on:
    branch: master
    # tags: true
  provider: pypi
  user: pupil-labs
  password : $PYPI_APITOKEN
  distributions: "bdist_wheel"
